version: "3.0"

services:
  web:
    container_name: Main_Web_Console
    image: nginx
    volumes:
      - ./root/web/conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ":80"
    depends_on:
      - was
    environment:
      - USER_NAME=root

  was:
    container_name: Main_Was_Console
    image: tomcat
    build:
      context: ./dockers
      dockerfile: dockerfile.was
    volumes:
      - ./root/was/data:/usr/local/tomcat/webapps/ROOT
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
    - USER_NAME=root

  db:
    container_name: Main_DB_Console
    image: mariadb
    build:
      context: ./dockers
      dockerfile: dockerfile.db
    volumes:
      - ./root/db/data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: abcd
      - USER_NAME=root
    

