# Generated by Django 3.2.12 on 2023-11-29 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20231127_0348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
