# Generated by Django 3.2.12 on 2023-11-29 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
